### ISSUE TITLE
Re-organizing the Dataset Labels

### ISSUE THREAD

**Issue by LinguList** [glottobank/lexibank-data#52]
This is a plea to re-think certain of the database labels, as the current names plus abbreviations are a bit ad-hoc. Ideally, we should search good abbreviations not exceeding 4 letters. But also the title should be indicative of content. So instead of "Andrew Kitchen et al.: Semitic languages", I'd suggest to call it "Semitic Basic Vocabulary Lists" (SBVL), as this will quickly tell that we are dealing with basic vocabulary, and with semitic. I adjusted the sources I added accordingly, but I suggest that before release we thoroughly discuss all names. Given that we only have 20 datasets so far (maybe 30 in the end for the start), we can afford to give it some proper discussion.

I would also suggest to put all abbreviations to upper case, as this looks nicer.

Here are my first suggestions, ad hoc, but let's add more if you have:

| old abbreviation | old dataset | new dataset (abbreviation) |
| --- | --- | --- |
| gbd | Grollemund Bantu Database |  Bantu Basic Vocabulary Lists (BBVL) |
| hrsa | Dataset of Huber and Reed's "Comparative Vocabulary" | Comparative Vocabulary of Columbian Languages (CVCL) |
|  num | Numeral Systems of the World's Languages | Numeral Systems of the World's Languages (NSWL) |
| agtupi | agtupi | Tupian Basic Vocabulary Lists (TBVL) |
| slja	| Sean Lee et al.: Japonic languages | Japonic Basic Vocabulary Lists  (JBVL) |
| wwua | The evolution and biogeography of Uto-Aztecan languages - supporting information | Uto-Aztekan Basic Vocabulary Lists (UABVL) |

As you see, forcing abbreviations containing things like BVL (basiv vocabulary list) will make it easier to determine what a dataset contains. And using a distinction between accompanying excel spreadsheets (Basic Vocabulary List) and published databases (Basic Vocabulary Database) may also be a good idea, and we also have the relevant sources closely together. 

Furthermore, I suggest that whenever filing a new issue for a new dataset, we suggest a title and an abbreviation in the issue.

**Comment by LinguList** [comment]
I was just thinking of this. I would suggest to call the first dataset:

* Cognates in Tupian Basic Lexicon (CTBL)

as this is the major purpose of the paper, and they don't have classical spreadsheets.

The second would then be called:

* Cognates in Tupian Cultural Lexicon (CTCL)

This is of course less consequent, but it seems like a nice description. As a general rule, I'd say we should have, if possible the language family in the titles we create, and no author names, as first authors are not necessarily the ones who made the cognates, etc.

For Paul Sidwell's data, I'd suggest now: Austro-Asiatic Dataset for Phylogenetic Analysis (ADPA), as this is also the title, without the author name.

**Comment by xrotwang** [comment]
What I meant was that this scheme doesn't work for multiple datasets of the
same things - which I think we'd like to support.
Am 28.08.2016 11:37 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by LinguList** [comment]
Well, we could break it down to three rules: 

1. do not use author names in the identifiers, unless it's in the title (Ruhlens Proto-World Survey, RPWS)
2. try to got for 3/4 letters in abbreviation, maximally 5
3. try to make a telling title that gives people an impression what the data might be

I know this is pretty qualitative, but I think the display will profit from it, and as long as we do not have too many datasets (and I suppose the datasets won't be more than 100 for the first couple of years, and if we are overrun, we need to find automatic identifiers anyway), we can do in this way.

**Comment by xrotwang** [comment]
Regarding different authors for cognate judgements, I'd suggest to split
into two datasets, because the dataset level is the most appropriate to
model common or distinct provenance.

As said elsewhere, it should be possible, to add a dataset providing
cognates only, and just referencing lexical data in a different dataset.
Maybe we should already follow this model for automatic cognates which we
add for datasets.
Am 28.08.2016 11:37 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by LinguList** [comment]
Yes, and I may actually have a usecase for this, the Bai Dialect Survey, #51, contains Allen's data, and my cognate sets super-imposed on it. It's all in one file now, also because the data was typed off of the PDF, but we can make this a first case illustrating how cognate sets are separated from the actual data. As a rule of thumb (as long as we stay qualitative in titles for datasets), we would have one dataset called Bai Dialect Survey (BDS) and one dataset called Cognates in Bai Dialect Survey (CBDS).

**Comment by LinguList** [comment]
Okay, with the new pr, we have bds in there, but I still need to synch the cognate judgments with it, as it turned out that I had some errors in the data. 

Question now is: should we generally add a new dataset for all automatic operations?

We have:

* segmentation, using clean_string (very important basis for reports, etc.)
* cognate judgments if missing, using Turchin (as it's fastest)
* alignments using SCA

Normally, we would add automatic cognates and alignments to BDS now, but since I want to add them manually, we would make a new dataset, called CBDS, only consisting of cognate sets with aligned entries, right?

**Comment by xrotwang** [comment]
Hm. Looking at your proposal for dataset identifiers again, I'm not convinced. It only seems slightly less ad-hoc than the current solution. Some problems:
- One letter abbreviations for language families won't cut it, I guess - `J` surely doesn't always mean `Japonic`.
- Why waste three letters on the resource type (`BVL`)?
- Is the distinction between "basic vocabulary lists" and "published databases" and "comparative vocabulary lists" really clear-cut and/or meaningful?

To me it seems to be more straightforward to solve the dataset identification problem with metadata. Even with just 30 datasets, I can't think of a "4-letter classification scheme" that is intuitive and transparent for the general linguistic public. So I see two ways to improve the situation:

Don't use the identifiers as directory names; but instead use something like the sluggified version of the title. This way, directory listings would still be meaningful for browsing datasets.

Or make it clear that directory listings don't help, and instead provide indexes to browse the data - e.g. a sortable table listing metadata as well in a markdown file, or a powerful `ls` like sub-command of `lexibank`. 

In both cases it may be helpful to switch to completely opaque identifiers - but I'm not entirely sure about this. In particular since some of the datasets already have well established short identifiers like `IDS`, `ABVD`, etc.

**Comment by xrotwang** [comment]
So if we go with some sort of descriptive classification scheme as identifiers (like in a library catalog), I would recommend to do this "properly", i.e. 
- compile a list of language-subgroup-to-abbr mappings (possibly including an abbreviation for "global")
- put together a controlled vocabulary of resource types, and identifiers
- have a specified way to deal with disambiguation, e.g. `jbvl1`, `jbvl2`.

Btw.: I find all uppercase identifiers just hard to type :)

**Comment by LinguList** [comment]
I figured we might actually quickly end up with 50 and more datasets, given how many are still out there, so the "qualitative" way would cause pain sooner or later. What I think at least is that the current way is way too ad hoc, sometimes listing database names, sometimes giving internal names, like "Grollemund Bantu Database". So thinking of a principled way to deal with this is in order, I'd say.

What is important is to note that a publication with SupMat is not the same as the dataset in the SupMat, so we should not use the title of the publication to give the dataset a name. Or, let's say, we should allow that the dataset name differs, especially if authors indicate this (or wish it). And often, people give a name to their dataset in their publication. So I'm more concerned with the title than the abbreviation. So I'd suggest that the title is as a default the title of the publication (nothing else), but it can be overwritten by explicitly using another title, if this seems appropriate (e.g., the authors indicate this, etc.).

Furthermore, we might consider adding a short note in the metadata.json, explaining the whereabouts of the data, just as we did for concepticon. I'd volunteer to do this in those cases where I know (not today, but the more we advance).

* As to your suggestion: the language-subgroup-to-abbreviation mapping has the one problem that we may have unrelated languages, like in the Kessler-Data, which is included in BDPA dataset now. But we could reserve an identifer for this.

* Resource types and identifiers should be possible.

* For disambiguation, we could use concept number and number of language varieties, plus the specified way in the very rare cases where the two coincide.

**Comment by LinguList** [comment]
Ah, as to uppercase: I agree, but on the web-app, it would look better, so I'd just suggest to switch to uppercase there (but note that this is my personal perception of abbreviations, and I don't insist on it).

**Comment by xrotwang** [comment]
Thinking a bit more, I'd just say the kinds of semantic identifiers you are proposing are wrong, because they don't reflect what a dataset is. A `lexibank` dataset for me is a bunch of lexical data with a shared provenance (which we exploit in the `download` command) and thus with a shared way of attribution (and presumably a shared way of updating). Whether the data relates to a certain (let alone a single) language family or was published in a certain way isn't essential (although it is of course useful metadata).

So from this point of view, the most semantically adequate identifier for the IDS or ABVD datastes would be ... `IDS` and `ABVD`. I.e. if identifiers should be mnemonic or semantic, the should be abbreviations of the way linguists refer to the underlying datasets already (which makes "Grollemund Bantu Database" probably somewhat less ad-hoc). Unfortunately these identifiers don't fit any of the principled schemes we discussed so far.

So I really don't know. I guess I'm leaning towards opaque 4-letter (maybe random) strings, and spending more effort on getting the title (and other metadata) right. I think in the long run, making sure directory names or URLs don't have to be changed because of debatable or incorrect semantics in them is more pragmatic, and thus more useful as a guidance for which identifiers to chose.

**Comment by LinguList** [comment]
I just tried to come up with a first list of resource types, but I think its useless, as it is too fuzzy:

Name | Abbr | note | example 
--- | --- | --- | --- 
multi-lingual wordlist(s) | mlwl (?) | wordlist without specifying any specific meaning range and usually not tagged for cognacy | IDS
mono-lingual wordlist | ? | wordlist for a single language family, e.g., extracted from a dictionary |  not yet given, but could be possible, especially when dealing with word families, etc.
basic vocabulary list | ? | a wordlist that was compiled for the purpose of lexicostatistic investigation, that is, it has more than one language, it has a meaning range that should be "basic" (whatever that is), and cognates should be indicated | ABVD, Grollemund Bantu, actually most of our lists
etymological dictionary | ? | usually a set of cognate entries of potentially different meanings centered around a proto-form | Siouan dictionary
aligned cognate sets | ? | this is a very special type, where cognate sets are explicitly aligned | Payne 1991

I agree now, that these semantic identifiers don't really work. And there are more important things to be done than to try finding out how to classify our resources (given that we want to classify the languages in the world ;-). For me, more important, is to work on a good title, and potentially also adding a note, as we did for the concept lists in concepticon (to render it mroe personal). The abbreviation is not that important, but the titles are at least in the current version often not very telling and giving a very ad-hoc impression, and if we stick to the schema: default = title of paper, but allow to overwrite by editors or contributors, this would be fine with me.

**Comment by LinguList** [comment]
And I won't rename any more folders. Promise.

**Comment by xrotwang** [comment]
Maybe we should follow the [bio2rdf model](http://download.bio2rdf.org/release/3/release.html), where identifiers are "as mnemonic as possible" and all-lowercase ascii (it seems); e.g. PubMed's ID is aptly `pubmed`. So for lexibank, this would mean, the `hgld` becomes `huntergatherer`, `num` becomes `numerals`, `psaa` becomes `sidwellaustroasiatic`.

**Comment by LinguList** [comment]
This looks fine to me, and they also keep the already established abbreviations, which would mean that abvd is just abvd.

**Comment by xrotwang** [comment]
Ok. So if we can agree on new identifiers now, I'd merge your PR and then do the renaming and be done with it?

- **uabvd** keep
- **num** -> **numerals**
- **psaa** -> **sidwellaustroasiatic**
- **slja** -> **leejaponic**
- **bbvd** -> **bantubvd**
- **wold** keep
- **wwua** -> **wheelerutoaztecan**
- **hgld** -> **huntergatherer**
- **pcbd** -> ?
- **cbvl** -> ?
- **acbd** keep
- **csd** keep
- **bdpa** keep
- **tng** -> **transnewguinea**
- **agtupi** -> **galuciotupi**
- **pollex** keep
- **abvd** keep
- **cddb** -> ?
- **tcwl** -> ?
- **gbd** -> **grollemundbantu**
- **ids** keep
- **mbvd** -> **mayanbvd**
- **hrsa** -> **huberandreed**
- **akse** -> **kitchenersemitic**

**Comment by LinguList** [comment]
Yes, let me add my suggestions:

- **uabvd** keep
- **num** -> **numerals**
- **psaa** -> **sidwellaustroasiatic**
- **slja** -> **leejaponic**
- **bbvd** -> **bantubvd**
- **wold** keep
- **wwua** -> **wheelerutoaztecan**
- **hgld** -> **huntergatherer**
- **pcbd** -> partialcognates
- **cbvl** -> chinesebasvoc
- **acbd** keep
- **csd** keep
- **bdpa** keep
- **tng** -> **transnewguinea**
- **agtupi** -> **galuciotupi**
- **pollex** keep
- **abvd** keep
- **cddb** -> sindial
- **tcwl** -> tukanoaligned
- **gbd** -> **grollemundbantu**
- **ids** keep
- **mbvd** -> **mayanbvd**
- **hrsa** -> **huberandreed**
- **akse** -> **kitchensemitic**

note that I also replaced "kitchenersemitic" with "kitchensemitic"

**Comment by LinguList** [comment]
There's also now:

* bds: baidialectsurvey
* cbds: ? [maybe leave it for the moment, as we're still discussing cross-referencing stuff, so this dataset may well change]

**Comment by xrotwang** [comment]
ok. I guess the two of us constitute a majority to decide this issue :)

**Comment by LinguList** [comment]
:-)

BTW: should I add a dc:note to the metadata, to add some short description of the dataset in concepticon style (also potentially cross-referencing, like "these are cognate sets built upon the dataset by xyz"), or should we make a global csv file, or use another tag?

**Comment by xrotwang** [comment]
dc:note (in markdown) in metadata.json seems perfect.

**Comment by xrotwang** [comment]
But wait for my PR to reorg the identifiers.

**Comment by LinguList** [comment]
ah, sorry, one more update on "cddb": could you abbreviate it as "yinku", as this is the name that is most mnemonic for linguists working on Chinese...

**Comment by LinguList** [comment]
"yinku" means "phon[etic data]base"

**Comment by xrotwang** [comment]
ok.

**Comment by SimonGreenhill** [comment]
Following this conversation, I'm happy with where we've arrived.
