### ISSUE TITLE
Add a dataset specific report to the website for enhanced error checking.

### ISSUE THREAD

**Issue by SimonGreenhill** [glottobank/lexibank-data#68]
e.g. list all CLPA/CLDF errors etc.

**Comment by LinguList** [comment]
we have it in the transcription.json file, tracked for each language, and we can from there easily enhance verbosity. E.g., what is interesting is type/token frequency, as it turns out, that most bad-ass errors only occur once, etc.

**Comment by LinguList** [comment]
Ideally, for practical purpose, we'd have a tabular HTML which can be sorted in different dimensions. I'm thinking of, say, things like all CLDF data with errors highlighted, all errors, but clickable, so that you can see which words show the error, etc.

In the lexibank app, it might be easiest to include the Segments column in the language-view, and to highlight errors interactively, be it by using the alignment-markup for the representation of segments, which would correspond more or less to lingpy's tolerance, be it by using some specific marker as output of the clean_string function, that indicates, whether a string is accepted by lingpy / clpa, or not. With a hierarchy of four states, higher implying lower, namely (1) clpa pure >> (2) clpa converted >> (3) lingpy >> (4) ?, we could mark errors by either adding them to the Segments, or by adding another column, indicating the status of each segment.

First solution could be done like this:

```text
string:                 thoxtA
segments:          th o x t A
error-annotated: th_₂ o_₁ x_₁ A_₄
```  
The second would just be:

```
string:                 thoxtA
segments:          th o x t A
error-annotion: 2 1 1 4
```

**Comment by LinguList** [comment]
actually, I was just thinking, this would even be really cool, as one could add sound information to each segment, linked to CLPA or the like, or popping up when hovering over the data. And instead of the numbers, adding clpa identifiers would just do the trick.

**Comment by xrotwang** [comment]
So it sounds (in particular @LinguList's comments about linking/hover effects, etc.) as if we are talking about features of the app at lexibank.clld.org, right? While I think linking to CLPA, including sound information and the like are good ideas, I think all curation-related things, e.g. error checking, should be handled in the repository. I see the app as the showcase for strictly quality controlled subset of lexibank data. So far this is true for the Glottolog and Concepticon mappings (only fully mapped CLDF rows are imported), but maybe at some point this should also be true for the transcription quality.

**Comment by LinguList** [comment]
I agree, and I think we can think of alternative tools for error-checking, if people desire to work on them. E.g., using lingpy as a standalone, integrating things into CLDF or into CLPA, as it is there, where we have discussions on quality. The hover-stuff would only be something that would help myself a lot, I think, although it is actually already sufficient to just use my [EDICTOR](http://edictor.digling.org) tool, as this highlights all errors and allows for immediate manual correction. 

Regarding the quality check: I'd say that we allow for some kind of a cut-off, maybe on a per-language (per variety) basis, we could cease to show the alignments and the like. This would circumvent alignment problems in ABVD, as some languages will pass the 90%, and it would be a service also to the users, as they could choose those data for benchmark stuff, and testing of new algos. By 90%, I think we should say: 90% of words should pass LingPy.
